#!/usr/bin/env bash
set -euo pipefail

# A very quick wrapper around the dots.tts REST API that Qwen stood up.
# You need to supply a reference_audio.wav and a reference_transcript.txt
#     reference_audio.wav: 8-12s of very clear speech
#     reference_transcript.txt: (one line) an exact transcript of the ref audio
# These are used for voice cloning.
#
# Pass any string argument to synthesize:
#   Example: speak.sh "Hello there, how are you today?"
#
# The output is given to aplay for immediate output.
#
# Requirements:
#   aplay (for outputting audio)
#   jq (for parsing/forming json)
#   base64 (for encoding/decoding audio payload)
#   curl (for POSTing up to the server)
#
# Generated by Qwen 3.6 27B Q6

# Colors for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Our dots.tts synthesis endpoint, adjust as needed:
SERVER_URL="http://saturn-lm:8000/synthesize"

# Our voice clone reference sample and transcript:
# (you need 8-12s of clean audio of someone speaking,
#  and an exact text transcript of what they're saying)
REFERENCE_AUDIO="/home/scorbett/Videos/editing/noplacelikelocalhost/ep010/audio/reference_audio.wav"
REFERENCE_TRANSCRIPT="/home/scorbett/Videos/editing/noplacelikelocalhost/ep010/audio/reference_transcript.txt"

usage() {
    echo "Usage: $0 <textToSpeak>"
    echo ""
    echo "Arguments:"
    echo "  <textToSpeak>   Any text you want to hear"
    echo ""
    echo "Example:"
    echo "  $0 \"Well, hello there. How are you?\""
    exit 1
}

# Check requirements:
for cmd in jq curl base64 aplay; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "Error: $cmd is required but not installed."; exit 1; }
done

# Check argument count
[[ $# -lt 1 || $# -gt 2 ]] && usage

# Validate input files exist
for f in "$REFERENCE_AUDIO" "$REFERENCE_TRANSCRIPT"; do
    if [[ ! -f "$f" ]]; then 
        echo -e "${RED}Error: File not found: $f${NC}"; 
        exit 1; 
    fi
done

# Sanitize transcript: replace newlines with spaces, collapse multiple spaces, trim
PROMPT_TEXT=$(tr '\n' ' ' < "$REFERENCE_TRANSCRIPT" | sed 's/  */ /g; s/ *$//')
TEXT_TO_SPEAK="$1"

# Base64 encode the reference WAV (single line)
echo -e "${GREEN}Encoding reference audio...${NC}"
REF_AUDIO_B64=$(base64 -w 0 < "$REFERENCE_AUDIO")

# Build JSON payload using jq
# We pass small strings as --arg, and pipe the large base64 audio via stdin
echo -e "${GREEN}Constructing request payload...${NC}"
PAYLOAD=$(echo "$REF_AUDIO_B64" | jq -R \
    --arg text "$TEXT_TO_SPEAK" \
    --arg prompt_text "$PROMPT_TEXT" \
    '{text: $text, prompt_text: $prompt_text, audio_base64: ., seed: null, num_steps: 12}')

# Temp: for debugging only... remove once solution works
#echo "Writing payload to payload.json"
#echo "$PAYLOAD" > payload.json

# Send POST request to the FastAPI server
# Using `-d @-` tells curl to read the payload from stdin, avoiding ARG_MAX limits
echo -e "${GREEN}Sending synthesis request to $SERVER_URL ...${NC}"
RESPONSE=$(echo "$PAYLOAD" | curl -s -w "\n%{http_code}" -X POST "$SERVER_URL" \
    -H "Content-Type: application/json" \
    -d @-)

# Separate HTTP status code from JSON response
HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
JSON_BODY=$(echo "$RESPONSE" | sed '$d')

# Check HTTP status
if [[ "$HTTP_CODE" -ne 200 ]]; then
    echo -e "${RED}Error: Server returned HTTP $HTTP_CODE${NC}"
    echo -e "${YELLOW}Response:${NC}"
    echo "$JSON_BODY" | jq . 2>/dev/null || echo "$JSON_BODY"
    exit 1
fi

# Extract base64 audio from response
echo -e "${GREEN}Extracting audio from response...${NC}"
AUDIO_B64=$(echo "$JSON_BODY" | jq -r '.audio_base64')

if [[ -z "$AUDIO_B64" || "$AUDIO_B64" == "null" ]]; then
    echo -e "${RED}Error: No audio_base64 field in response${NC}"
    echo "$JSON_BODY" | jq .
    exit 1
fi

# Decode base64 and save as WAV
echo -e "${GREEN}Decoding audio and saving to $OUTPUT_WAV ...${NC}"
TMPFILE=$(mktemp)
echo "$AUDIO_B64" | base64 -d > "$TMPFILE"
# Verify output file was created and is non-empty
if [[ -s "$TMPFILE" ]]; then
    echo -e "${GREEN}✅ Successfully received synthesized audio${NC}"

    # Optionally print server metrics if available
    METRICS=$(echo "$JSON_BODY" | jq -r '.time_used, .rtf, .sample_rate' 2>/dev/null)
    if [[ -n "$METRICS" ]]; then
        echo -e "${YELLOW}📊 Server Metrics:${NC}"
        echo "$METRICS" | while IFS= read -r line; do
            echo "   $line"
        done
    fi
else
    echo -e "${RED}Error: Output file is empty or was not created${NC}"
    exit 1
fi

# Now play it!
aplay "$TMPFILE"

# Cleanup:
rm "$TMPFILE"

